/* Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. */
package org.apache.sysds.test.component.federated.placement.guard;
import java.util.*;import org.junit.Assert;import org.junit.Test;
import org.apache.sysds.hops.fedplanner.placement.NeutralPlacementGraphBuilder;
import org.apache.sysds.test.component.federated.placement.shadow.ProductionShadowFixtureFactory;
/** Exact executable RED for scoped Heuristic no-refed provenance. */
public class CampaignBHeuristicProvenanceContractTest {

 @Test public void h01DescendantRefederationCandidateIsRemovedFromSelectorGraph()throws Exception{var f=CampaignBProvenanceFixtureBridge.fresh("H-01-TWRITE-TREAD");var s=R4Heuristic2AdapterBridge.select(f.analysis(),Set.of(f.marker()));for(String removed:f.removedCandidates())Assert.assertFalse("H-01 descendant refederated candidate must be absent from selector graph: "+removed,s.selectorCandidates().contains(selectorCandidate(removed)));for(var key:f.descendants())Assert.assertFalse("H-01 descendant assignment cannot refederate "+key,isRefederated(s.assignments().get(key.normalizedSignature())));}

 @Test public void h02H03DescendantRefederationCandidatesAreRemovedFromSelectorGraph()throws Exception{for(String id:List.of("H-02-BRANCH-JOIN","H-03-LOOP-RECOMPILE")){var f=CampaignBProvenanceFixtureBridge.fresh(id);var s=R4Heuristic2AdapterBridge.select(f.analysis(),Set.of(f.marker()));for(String removed:f.removedCandidates())Assert.assertFalse(id+" descendant refederated candidate must be absent from selector graph: "+removed,s.selectorCandidates().contains(selectorCandidate(removed)));for(var key:f.descendants())Assert.assertFalse(id+" descendant assignment cannot refederate "+key,isRefederated(s.assignments().get(key.normalizedSignature())));}}
 @Test public void h09IndependentCandidateRetainsFedFoutWhileDescendantsDoNot()throws Exception{var f=CampaignBProvenanceFixtureBridge.fresh("H-09-INDEPENDENT-ANCHOR-RELEASE");var s=R4Heuristic2AdapterBridge.select(f.analysis(),Set.of(f.marker()));String y=f.roles().get("Y_INDEPENDENT").normalizedSignature();Assert.assertTrue("H-09 independent Y keeps FED/FOUT selector availability",statesFor(s.selectorCandidates(),y).stream().anyMatch(CampaignBHeuristicProvenanceContractTest::isFedFout));Assert.assertTrue("H-09 independent Y selected FED/FOUT",isFedFout(s.assignments().get(y)));for(var key:f.descendants()){Assert.assertFalse("H-09 descendant assignment cannot refederate "+key,isRefederated(s.assignments().get(key.normalizedSignature())));Assert.assertTrue("H-09 descendant has at least one non-refed selector state "+key,statesFor(s.selectorCandidates(),key.normalizedSignature()).stream().anyMatch(state->!isRefederated(state)));}}
 @Test public void nonEmittedFunctionTraceNodesStayOutsideHeuristicDecisionProjection()throws Exception{List<String>failures=new ArrayList<>();for(String id:List.of("B-07","B-08","B-17","B-21")){var analysis=new NeutralPlacementGraphBuilder().buildAnalysis(ProductionShadowFixtureFactory.compile(id));var keys=R4SharedFedAllSemanticValidator.decisionKeys(analysis.graph()).stream().map(x->x.normalizedSignature()).collect(java.util.stream.Collectors.toSet());Assert.assertTrue(id+" must preserve trace nodes",analysis.graph().nodes().stream().anyMatch(n->!n.emittedWork()&&n.legalAlternatives().isEmpty()));Assert.assertEquals(id,analysis.graph().nodes().size(),analysis.occurrences().size());try{var actual=R4Heuristic2AdapterBridge.select(analysis,Set.of());Assert.assertEquals(id,keys,actual.assignments().keySet());Assert.assertEquals(id,analysis.analysisFingerprint(),actual.analysisFingerprint());}catch(Throwable failure){failures.add("HEURISTIC_DECISION_PROJECTION_THROW|"+id+'|'+failure.getClass().getName()+'|'+failure.getMessage());}}Assert.assertEquals("all four actual function fixtures must select",List.of(),failures);}
 @Test public void allTenLiteralFixturesRequireExactStablePolicySelections()throws Exception{List<String>missing=new ArrayList<>();for(String id:CampaignBProvenanceFixtureBridge.ids()){var f=CampaignBProvenanceFixtureBridge.fresh(id);var before=R4Heuristic2Probe.snapshot(f.program(),f.analysis());try{var a=R4Heuristic2AdapterBridge.select(f.analysis(),Set.of(f.marker()));R4Heuristic2SemanticValidator.heuristic(f,a);var repeat=R4Heuristic2AdapterBridge.select(f.analysis(),Set.of(f.marker()));Assert.assertEquals("repeat stable",a,repeat);var fresh=CampaignBProvenanceFixtureBridge.fresh(id);var b=R4Heuristic2AdapterBridge.select(fresh.analysis(),Set.of(fresh.marker()));R4Heuristic2SemanticValidator.heuristic(fresh,b);Assert.assertEquals("fresh plan stable",a.planFingerprint(),b.planFingerprint());}catch(AssertionError e){if(String.valueOf(e.getMessage()).startsWith("CAMPAIGN_B_RUNTIME_ADAPTER_MISSING"))missing.add(id+'|'+e.getMessage());else throw e;}R4Heuristic2Probe.unchanged(before,R4Heuristic2Probe.snapshot(f.program(),f.analysis()));}Assert.assertEquals("CAMPAIGN_B_RUNTIME_ADAPTER_MISSING",List.of(),missing);}
 @Test public void exactExclusionH09H10FingerprintAndNestedMutationShortcutsFail()throws Exception{var h9=CampaignBProvenanceFixtureBridge.fresh("H-09-INDEPENDENT-ANCHOR-RELEASE");var good=fake(h9);List<String>extra=new ArrayList<>(good.exclusions());extra.add("NO_REFED|EXTRA_GLOBAL|"+h9.roles().get("Y_INDEPENDENT").normalizedSignature());expect("exact exclusions",()->R4Heuristic2SemanticValidator.heuristic(h9,copy(good,good.assignments(),extra,good.certificate(),good.candidates())));Map<String,String>global=new LinkedHashMap<>(good.assignments());String y=h9.roles().get("Y_INDEPENDENT").normalizedSignature();global.put(y,"CP/LOUT/-/SHAPE_INDEPENDENT");expect("H-09 Y FED/FOUT",()->R4Heuristic2SemanticValidator.heuristic(h9,copy(good,global,good.exclusions(),good.certificate(),good.candidates())));
  expect("non-vacuous exclusions",()->R4Heuristic2SemanticValidator.heuristic(h9,copy(good,good.assignments(),List.of(),good.certificate(),good.candidates())));
  var h10=CampaignBProvenanceFixtureBridge.fresh("H-10-SAME-SHAPE-DISTINCT-ANCHORS");var ten=fake(h10);List<String>con=new ArrayList<>(ten.exclusions());con.add("NO_REFED|"+h10.anchors().get("ANCHOR_B").normalizedSignature());expect("exact exclusions",()->R4Heuristic2SemanticValidator.heuristic(h10,copy(ten,ten.assignments(),con,ten.certificate(),ten.candidates())));var badCert=new R4Heuristic2AdapterBridge.Certificate(ten.certificate().baseGraphFingerprint(),"WRONG",ten.certificate().assignmentHash(),ten.certificate().universe(),ten.certificate().explored(),ten.certificate().pruned(),ten.certificate().bounds(),ten.certificate().incumbent(),ten.certificate().upperBound(),ten.certificate().termination(),false);expect("policyViewFingerprint",()->R4Heuristic2SemanticValidator.heuristic(h10,copy(ten,ten.assignments(),ten.exclusions(),badCert,ten.candidates())));var mutable=new ArrayList<>(ten.candidates());expect("mutable list",()->R4Heuristic2SemanticValidator.heuristic(h10,copy(ten,ten.assignments(),ten.exclusions(),ten.certificate(),mutable)));}
 static String selectorCandidate(String candidate){int i=candidate.lastIndexOf('=');return i<0?candidate:token(candidate.substring(0,i))+"|"+token(candidate.substring(i+1));}
 static String token(String value){return value.length()+":"+value;}
 static boolean isRefederated(String s){return s!=null&&s.contains("FOUT")&&(s.contains("CP")||s.contains("FED"));}
 static List<String> statesFor(List<String> candidates,String key){List<String> states=new ArrayList<>();String prefix=token(key)+"|";for(String candidate:candidates)if(candidate.startsWith(prefix)){String encodedState=candidate.substring(prefix.length());int colon=encodedState.indexOf(':');if(colon<1)throw new AssertionError("malformed normalized candidate "+candidate);int length=Integer.parseInt(encodedState.substring(0,colon));String value=encodedState.substring(colon+1);if(value.length()!=length)throw new AssertionError("malformed normalized candidate "+candidate);states.add(value);}return states.stream().sorted().toList();}
 static boolean isFedFout(String s){return s!=null&&s.contains("FED")&&s.contains("FOUT");}

 static R4Heuristic2AdapterBridge.Selection fake(CampaignBProvenanceFixtureBridge.Fixture f)throws Exception{List<String>c=R4Heuristic2SemanticValidator.expectedCandidates(f),e=R4Heuristic2SemanticValidator.expectedExclusions(f);Map<String,String>a=new TreeMap<>();for(var n:f.analysis().graph().nodes()){String k=n.key().normalizedSignature();String state=firstState(c,k,s->!s.contains("CP/FOUT"));a.put(k,state);}if(f.id().contains("INDEPENDENT")){String y=f.roles().get("Y_INDEPENDENT").normalizedSignature();a.put(y,firstState(c,y,s->s.contains("FED")&&s.contains("FOUT")));}List<String>anchors=f.analysis().graph().nodes().stream().flatMap(n->n.anchors().stream()).map(x->x.normalizedSignature()).distinct().sorted().toList();String ah=R4Heuristic2SemanticValidator.assignmentHash(a);var z=new R4Heuristic2AdapterBridge.Certificate(f.analysis().analysisFingerprint(),R4Heuristic2SemanticValidator.policyViewFingerprint(f,c,e),ah,c.size(),c.size(),0,List.of("complete"),"best","best","EXHAUSTED",false);return copy(new R4Heuristic2AdapterBridge.Selection(f.analysis(),"FED_HEURISTIC",f.analysis().analysisFingerprint(),Map.copyOf(a),Map.copyOf(a),c,c,e,List.of(),List.of(),List.of(),anchors,List.of(),List.of(),List.of(),List.of(),List.of(),List.of(),List.of(),List.of(),List.of(),Map.of(),z,z.toString(),""),a,e,z,c);}
 static R4Heuristic2AdapterBridge.Selection copy(R4Heuristic2AdapterBridge.Selection s,Map<String,String>a,List<String>e,R4Heuristic2AdapterBridge.Certificate z,List<String>c)throws Exception{var x=new R4Heuristic2AdapterBridge.Selection(s.analysis(),s.plannerId(),s.analysisFingerprint(),Collections.unmodifiableMap(new TreeMap<>(a)),Collections.unmodifiableMap(new TreeMap<>(a)),c,s.selectorCandidates(),e,s.relocations(),s.selectedLocals(),s.obligations(),s.anchors(),s.refedRegistry(),s.foutRegistry(),s.localRegistry(),s.objective(),s.ties(),s.trtw(),s.boundaries(),s.clones(),s.structural(),s.plannerFacts(),z,s.objectiveCertificate(),"");return new R4Heuristic2AdapterBridge.Selection(x.analysis(),x.plannerId(),x.analysisFingerprint(),x.assignments(),x.emissionAssignments(),x.candidates(),x.selectorCandidates(),x.exclusions(),x.relocations(),x.selectedLocals(),x.obligations(),x.anchors(),x.refedRegistry(),x.foutRegistry(),x.localRegistry(),x.objective(),x.ties(),x.trtw(),x.boundaries(),x.clones(),x.structural(),x.plannerFacts(),x.certificate(),x.objectiveCertificate(),R4Heuristic2SemanticValidator.planFingerprint(x));}
	 static String firstState(List<String>c,String k,java.util.function.Predicate<String>p){List<String>states=R4Heuristic2SemanticValidator.statesFor(c,k);return states.stream().filter(p).findFirst().orElseGet(()->states.stream().findFirst().orElseThrow());}
 static void expect(String text,Throwing x)throws Exception{try{x.run();Assert.fail("shortcut passed "+text);}catch(AssertionError e){Assert.assertTrue(String.valueOf(e.getMessage()),String.valueOf(e.getMessage()).contains(text));}}interface Throwing{void run()throws Exception;}
}
