/* Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. */
package org.apache.sysds.test.component.federated.placement.guard;
import java.util.*;import org.junit.Assert;import org.junit.Test;
/** Exact executable RED for scoped Heuristic no-refed provenance. */
public class CampaignBHeuristicProvenanceContractTest {
 @Test public void allTenLiteralFixturesRequireExactStablePolicySelections()throws Exception{List<String>missing=new ArrayList<>();for(String id:CampaignBProvenanceFixtureBridge.ids()){var f=CampaignBProvenanceFixtureBridge.fresh(id);var before=R4Heuristic2Probe.snapshot(f.program(),f.analysis());try{var a=R4Heuristic2AdapterBridge.select(f.analysis(),Set.of(f.marker()));R4Heuristic2SemanticValidator.heuristic(f,a);var repeat=R4Heuristic2AdapterBridge.select(f.analysis(),Set.of(f.marker()));Assert.assertEquals("repeat stable",a,repeat);var fresh=CampaignBProvenanceFixtureBridge.fresh(id);var b=R4Heuristic2AdapterBridge.select(fresh.analysis(),Set.of(fresh.marker()));R4Heuristic2SemanticValidator.heuristic(fresh,b);Assert.assertEquals("fresh plan stable",a.planFingerprint(),b.planFingerprint());}catch(AssertionError e){if(String.valueOf(e.getMessage()).startsWith("CAMPAIGN_B_RUNTIME_ADAPTER_MISSING"))missing.add(id+'|'+e.getMessage());else throw e;}R4Heuristic2Probe.unchanged(before,R4Heuristic2Probe.snapshot(f.program(),f.analysis()));}Assert.assertEquals("CAMPAIGN_B_RUNTIME_ADAPTER_MISSING",List.of(),missing);}
 @Test public void exactExclusionH09H10FingerprintAndNestedMutationShortcutsFail()throws Exception{var h9=CampaignBProvenanceFixtureBridge.fresh("H-09-INDEPENDENT-ANCHOR-RELEASE");var good=fake(h9);List<String>extra=new ArrayList<>(good.exclusions());extra.add("NO_REFED|EXTRA_GLOBAL|"+h9.roles().get("Y_INDEPENDENT").normalizedSignature());expect("exact exclusions",()->R4Heuristic2SemanticValidator.heuristic(h9,copy(good,good.assignments(),extra,good.certificate(),good.candidates())));Map<String,String>global=new LinkedHashMap<>(good.assignments());String y=h9.roles().get("Y_INDEPENDENT").normalizedSignature();global.put(y,"CP/LOUT/-/SHAPE_INDEPENDENT");expect("H-09 Y FED/FOUT",()->R4Heuristic2SemanticValidator.heuristic(h9,copy(good,global,good.exclusions(),good.certificate(),good.candidates())));
  expect("non-vacuous exclusions",()->R4Heuristic2SemanticValidator.heuristic(h9,copy(good,good.assignments(),List.of(),good.certificate(),good.candidates())));
  var h10=CampaignBProvenanceFixtureBridge.fresh("H-10-SAME-SHAPE-DISTINCT-ANCHORS");var ten=fake(h10);List<String>con=new ArrayList<>(ten.exclusions());con.add("NO_REFED|"+h10.anchors().get("ANCHOR_B").normalizedSignature());expect("exact exclusions",()->R4Heuristic2SemanticValidator.heuristic(h10,copy(ten,ten.assignments(),con,ten.certificate(),ten.candidates())));var badCert=new R4Heuristic2AdapterBridge.Certificate(ten.certificate().baseGraphFingerprint(),"WRONG",ten.certificate().assignmentHash(),ten.certificate().universe(),ten.certificate().explored(),ten.certificate().pruned(),ten.certificate().bounds(),ten.certificate().incumbent(),ten.certificate().upperBound(),ten.certificate().termination(),false);expect("policyViewFingerprint",()->R4Heuristic2SemanticValidator.heuristic(h10,copy(ten,ten.assignments(),ten.exclusions(),badCert,ten.candidates())));var mutable=new ArrayList<>(ten.candidates());expect("mutable list",()->R4Heuristic2SemanticValidator.heuristic(h10,copy(ten,ten.assignments(),ten.exclusions(),ten.certificate(),mutable)));}
 static R4Heuristic2AdapterBridge.Selection fake(CampaignBProvenanceFixtureBridge.Fixture f)throws Exception{List<String>c=R4Heuristic2SemanticValidator.expectedCandidates(f),e=R4Heuristic2SemanticValidator.expectedExclusions(f);Map<String,String>a=new TreeMap<>();for(var n:f.analysis().graph().nodes()){String k=n.key().normalizedSignature();String state=firstState(c,k,s->!s.contains("CP/FOUT"));a.put(k,state);}if(f.id().contains("INDEPENDENT")){String y=f.roles().get("Y_INDEPENDENT").normalizedSignature();a.put(y,firstState(c,y,s->s.contains("FED")&&s.contains("FOUT")));}List<String>anchors=f.analysis().graph().nodes().stream().flatMap(n->n.anchors().stream()).map(x->x.normalizedSignature()).distinct().sorted().toList();String ah=R4Heuristic2SemanticValidator.assignmentHash(a);var z=new R4Heuristic2AdapterBridge.Certificate(f.analysis().analysisFingerprint(),R4Heuristic2SemanticValidator.policyViewFingerprint(f,c,e),ah,c.size(),c.size(),0,List.of("complete"),"best","best","EXHAUSTED",false);return copy(new R4Heuristic2AdapterBridge.Selection(f.analysis(),f.analysis().analysisFingerprint(),Map.copyOf(a),c,e,List.of(),List.of(),anchors,List.of(),List.of(),List.of(),List.of(),List.of(),List.of(),List.of(),List.of(),List.of(),Map.of(),z,""),a,e,z,c);}
 static R4Heuristic2AdapterBridge.Selection copy(R4Heuristic2AdapterBridge.Selection s,Map<String,String>a,List<String>e,R4Heuristic2AdapterBridge.Certificate z,List<String>c)throws Exception{var x=new R4Heuristic2AdapterBridge.Selection(s.analysis(),s.analysisFingerprint(),Collections.unmodifiableMap(new TreeMap<>(a)),c,e,s.relocations(),s.obligations(),s.anchors(),s.refedRegistry(),s.foutRegistry(),s.localRegistry(),s.objective(),s.ties(),s.trtw(),s.boundaries(),s.clones(),s.structural(),s.plannerFacts(),z,"");return new R4Heuristic2AdapterBridge.Selection(x.analysis(),x.analysisFingerprint(),x.assignments(),x.candidates(),x.exclusions(),x.relocations(),x.obligations(),x.anchors(),x.refedRegistry(),x.foutRegistry(),x.localRegistry(),x.objective(),x.ties(),x.trtw(),x.boundaries(),x.clones(),x.structural(),x.plannerFacts(),x.certificate(),R4Heuristic2SemanticValidator.planFingerprint(x));}
 static String firstState(List<String>c,String k,java.util.function.Predicate<String>p){String q=k+'=';return c.stream().filter(x->x.startsWith(q)).map(x->x.substring(q.length())).filter(p).findFirst().orElseGet(()->c.stream().filter(x->x.startsWith(q)).findFirst().orElseThrow().substring(q.length()));}
 static void expect(String text,Throwing x)throws Exception{try{x.run();Assert.fail("shortcut passed "+text);}catch(AssertionError e){Assert.assertTrue(String.valueOf(e.getMessage()),String.valueOf(e.getMessage()).contains(text));}}interface Throwing{void run()throws Exception;}
}
