/* Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. */
package org.apache.sysds.test.component.federated.placement.guard;
import java.util.*;import org.junit.Assert;
/** Exact semantic validator: literal fixture commitments and independently recomputed policy proof. */
final class R4Heuristic2SemanticValidator {
 static void heuristic(CampaignBProvenanceFixtureBridge.Fixture f,R4Heuristic2AdapterBridge.Selection s)throws Exception{
  Assert.assertEquals(R4Heuristic2LiteralExpectations.exact(f.id()),CampaignBProvenanceFixtureBridge.literalDescription(f));Assert.assertSame("supplied analysis identity",f.analysis(),s.analysis());Assert.assertEquals(f.analysis().analysisFingerprint(),s.analysisFingerprint());
  List<String> candidates=expectedCandidates(f),exclusions=expectedExclusions(f);Assert.assertFalse("non-vacuous exclusions "+f.id(),exclusions.isEmpty());Assert.assertFalse("non-vacuous exclusions "+f.id(),s.exclusions().isEmpty());Assert.assertEquals("exact filtered candidates "+f.id(),candidates,s.candidates());Assert.assertEquals("exact exclusions "+f.id(),exclusions,s.exclusions());
  for(String relocation:f.removedRelocations())Assert.assertFalse("no-refed relocation selected",s.relocations().contains(relocation));
  for(var key:f.unrelated())Assert.assertEquals("unrelated alternatives "+key,f.baseAlternatives().get(key.normalizedSignature()),statesFor(s.candidates(),key.normalizedSignature()));
  Assert.assertEquals("complete assignment",f.analysis().graph().nodes().size(),s.assignments().size());
  for(var key:f.descendants()){String selected=s.assignments().get(key.normalizedSignature());Assert.assertNotNull("descendant missing "+key,selected);Assert.assertFalse("descendant refederated "+key,isRefederated(selected));}
  if(f.id().contains("INDEPENDENT")){String y=f.roles().get("Y_INDEPENDENT").normalizedSignature();Assert.assertTrue("H-09 Y FED/FOUT",isFedFout(s.assignments().get(y)));for(var key:f.descendants())Assert.assertFalse("H-09 X/Z no-refed",isRefederated(s.assignments().get(key.normalizedSignature())));}
  for(var e:s.assignments().entrySet())Assert.assertTrue("selected state outside filtered universe "+e,s.candidates().contains(e.getKey()+'='+e.getValue()));
  if(f.id().contains("DISTINCT-ANCHORS")){String a=f.anchors().get("ANCHOR_A").normalizedSignature(),b=f.anchors().get("ANCHOR_B").normalizedSignature();Assert.assertNotEquals(a,b);Assert.assertEquals(new TreeSet<>(List.of(a,b)),new TreeSet<>(s.anchors()));Assert.assertTrue("anchor A provenance absent",s.exclusions().stream().allMatch(x->x.contains("proof=")&&x.contains(a)));Assert.assertFalse("anchor B conflated",s.exclusions().stream().anyMatch(x->x.contains(b)));String bKey=f.roles().get("ANCHOR_B_NODE").normalizedSignature();Assert.assertTrue("anchor B FED/FOUT candidate retained",statesFor(s.candidates(),bKey).stream().anyMatch(R4Heuristic2SemanticValidator::isFedFout));}
  var c=s.certificate();Assert.assertEquals(f.analysis().analysisFingerprint(),c.baseGraphFingerprint());Assert.assertEquals("policyViewFingerprint",policyViewFingerprint(f,candidates,exclusions),c.policyViewFingerprint());Assert.assertEquals(candidates.size(),c.universe());Assert.assertEquals(c.universe(),c.explored()+c.pruned());Assert.assertEquals(c.incumbent(),c.upperBound());Assert.assertTrue(Set.of("EXHAUSTED","TIGHT_BOUND_EQUALITY").contains(c.termination()));Assert.assertFalse(c.fallback());Assert.assertEquals(assignmentHash(s.assignments()),c.assignmentHash());Assert.assertEquals(planFingerprint(s),s.planFingerprint());assertDeepImmutable(s);
 }
 static List<String> expectedCandidates(CampaignBProvenanceFixtureBridge.Fixture f){Set<String>x=new TreeSet<>();for(var e:f.baseAlternatives().entrySet())for(String state:e.getValue())x.add(e.getKey()+'='+state);x.removeAll(f.removedCandidates());return List.copyOf(x);}
 static List<String> expectedExclusions(CampaignBProvenanceFixtureBridge.Fixture f){return f.removedCandidates().stream().sorted().map(x->"NO_REFED|"+x+"|proof="+CampaignBProvenanceFixtureBridge.proofSignature(f.candidateProofs().get(x))+"|marker="+f.marker().normalizedSignature()).toList();}
 static String policyViewFingerprint(CampaignBProvenanceFixtureBridge.Fixture f,List<String>c,List<String>e)throws Exception{return R4Heuristic2Probe.sha256("NO_REFED_POLICY_V1|"+f.analysis().analysisFingerprint()+'|'+f.marker().normalizedSignature()+'|'+c+'|'+e);}
 static String assignmentHash(Map<String,String>a)throws Exception{return R4Heuristic2Probe.sha256(new TreeMap<>(a).toString());}
 static String planFingerprint(R4Heuristic2AdapterBridge.Selection s)throws Exception{return R4Heuristic2Probe.sha256(s.analysisFingerprint()+'|'+new TreeMap<>(s.assignments())+'|'+s.candidates()+'|'+s.exclusions()+'|'+s.relocations()+'|'+s.obligations()+'|'+s.anchors()+'|'+s.refedRegistry()+'|'+s.foutRegistry()+'|'+s.localRegistry()+'|'+s.objective()+'|'+s.ties()+'|'+s.trtw()+'|'+s.boundaries()+'|'+s.clones()+'|'+s.structural()+'|'+new TreeMap<>(s.plannerFacts()));}
 private static void assertDeepImmutable(R4Heuristic2AdapterBridge.Selection s){R4Heuristic2Probe.immutable(s.assignments());R4Heuristic2Probe.immutable(s.candidates());R4Heuristic2Probe.immutable(s.exclusions());R4Heuristic2Probe.immutable(s.relocations());R4Heuristic2Probe.immutable(s.obligations());R4Heuristic2Probe.immutable(s.anchors());R4Heuristic2Probe.immutable(s.refedRegistry());R4Heuristic2Probe.immutable(s.foutRegistry());R4Heuristic2Probe.immutable(s.localRegistry());R4Heuristic2Probe.immutable(s.objective());R4Heuristic2Probe.immutable(s.ties());R4Heuristic2Probe.immutable(s.trtw());R4Heuristic2Probe.immutable(s.boundaries());R4Heuristic2Probe.immutable(s.clones());R4Heuristic2Probe.immutable(s.structural());R4Heuristic2Probe.immutable(s.plannerFacts());R4Heuristic2Probe.immutable(s.certificate().bounds());}
 private static List<String> statesFor(List<String>a,String key){List<String>o=new ArrayList<>();String p=key+'=';for(String x:a)if(x.startsWith(p))o.add(x.substring(p.length()));return o.stream().sorted().toList();}
 private static boolean isRefederated(String s){return s!=null&&s.contains("FOUT")&&(s.contains("CP")||s.contains("FED"));}private static boolean isFedFout(String s){return s!=null&&s.contains("FED")&&s.contains("FOUT");}
 private R4Heuristic2SemanticValidator(){}
}
