/* Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. */
package org.apache.sysds.test.component.federated.placement.guard;
import java.lang.reflect.*;import java.util.*;import org.apache.sysds.hops.fedplanner.placement.PlacementAnalysis;import org.apache.sysds.hops.fedplanner.placement.PlacementIdentity.ValueVersionKey;
/** Heuristic-only reflection boundary; all result and certificate fields are mandatory and deeply normalized. */
final class R4Heuristic2AdapterBridge {
 private static final String POLICY_EXCEPTION="org.apache.sysds.hops.fedplanner.placement.adapter.HeuristicPolicySafetyException";
 private static final String MISSING_HOP_CODE="HEURISTIC_POLICY_SAFETY_REJECTION|reason=MISSING_HOP_PROJECTION";
 static final class TypedPolicySafetyRejection extends AssertionError {private final String causeType;private final String stableCode;TypedPolicySafetyRejection(Throwable cause){super(MISSING_HOP_CODE,cause);causeType=cause.getClass().getName();stableCode=String.valueOf(cause.getMessage());}String causeType(){return causeType;}String stableCode(){return stableCode;}}
 record Certificate(String baseGraphFingerprint,String policyViewFingerprint,String assignmentHash,long universe,long explored,long pruned,List<String>bounds,String incumbent,String upperBound,String termination,boolean fallback){}
 record Selection(PlacementAnalysis analysis,String analysisFingerprint,Map<String,String>assignments,List<String>candidates,List<String>exclusions,List<String>relocations,List<String>obligations,List<String>anchors,List<String>refedRegistry,List<String>foutRegistry,List<String>localRegistry,List<String>objective,List<String>ties,List<String>trtw,List<String>boundaries,List<String>clones,List<String>structural,Map<String,String>plannerFacts,Certificate certificate,String planFingerprint){}
 static Selection select(PlacementAnalysis analysis,Set<ValueVersionKey>markers){String name="org.apache.sysds.hops.fedplanner.placement.adapter.HeuristicPlacementAdapter";try{Class<?>c=Class.forName(name);Object a=c.getConstructor().newInstance();return normalize(c.getMethod("select",PlacementAnalysis.class,Set.class).invoke(a,analysis,copyMarkers(markers)));}catch(ClassNotFoundException|NoSuchMethodException e){throw new AssertionError("CAMPAIGN_B_RUNTIME_ADAPTER_MISSING|planner=HEURISTIC|class="+name);}catch(InvocationTargetException e){Throwable x=e.getCause();if(x instanceof RuntimeException&&POLICY_EXCEPTION.equals(x.getClass().getName())&&MISSING_HOP_CODE.equals(x.getMessage()))throw new TypedPolicySafetyRejection(x);throw new AssertionError("CAMPAIGN_B_ADAPTER_INVOCATION_FAILED|planner=HEURISTIC|cause="+x.getClass().getName());}catch(ReflectiveOperationException|RuntimeException e){throw new AssertionError("CAMPAIGN_B_REFLECTION_CONTRACT_BROKEN|planner=HEURISTIC|cause="+e.getClass().getName());}}
 static List<String> invocationOrder(Set<ValueVersionKey>markers){List<String>x=new ArrayList<>();for(ValueVersionKey marker:copyMarkers(markers))x.add(marker.normalizedSignature());return List.copyOf(x);}
 private static Set<ValueVersionKey>copyMarkers(Set<ValueVersionKey>markers){return Collections.unmodifiableSet(new LinkedHashSet<>(markers));}
 private static Selection normalize(Object r)throws ReflectiveOperationException{if(r==null)throw new AssertionError("CAMPAIGN_B_ADAPTER_RESULT_INCOMPLETE|accessor=result");PlacementAnalysis a=(PlacementAnalysis)get(r,"analysis");Object z=get(r,"certificate");Certificate c=new Certificate(str(z,"baseGraphFingerprint"),str(z,"policyViewFingerprint"),str(z,"assignmentHash"),num(z,"legalUniverseSize"),num(z,"exploredCount"),num(z,"prunedCount"),list(z,"bounds",false),str(z,"incumbentSignature"),str(z,"finalUpperBoundSignature"),str(z,"terminationReason"),bool(z,"fallbackUsed"));return new Selection(a,str(r,"analysisFingerprint"),map(r,"assignment"),list(r,"filteredCandidateUniverse",true),list(r,"policyExclusions",true),list(r,"selectedRelocations",true),list(r,"selectedObligations",true),list(r,"durableAnchors",true),list(r,"registryRefed",true),list(r,"registryFoutMaterialize",true),list(r,"registryLocalMaterialize",true),list(r,"objectiveComponents",false),list(r,"orderedTieBreaks",false),list(r,"transientRelationships",true),list(r,"controlBoundaryFacts",true),list(r,"cloneRecompileMultiplicities",true),list(r,"structuralExclusions",true),stringMap(r,"plannerFacts"),c,str(r,"normalizedPlanFingerprint"));}
 private static Object get(Object o,String n)throws ReflectiveOperationException{try{return o.getClass().getMethod(n).invoke(o);}catch(NoSuchMethodException e){throw new AssertionError("CAMPAIGN_B_ADAPTER_RESULT_INCOMPLETE|accessor="+n);}}private static String str(Object o,String n)throws ReflectiveOperationException{return String.valueOf(get(o,n));}private static long num(Object o,String n)throws ReflectiveOperationException{return((Number)get(o,n)).longValue();}private static boolean bool(Object o,String n)throws ReflectiveOperationException{return(Boolean)get(o,n);}private static String sig(Object x)throws ReflectiveOperationException{return x instanceof String?(String)x:str(x,"normalizedSignature");}private static List<String>list(Object o,String n,boolean sort)throws ReflectiveOperationException{List<String>x=new ArrayList<>();for(Object v:(Iterable<?>)get(o,n))x.add(sig(v));if(sort)Collections.sort(x);return List.copyOf(x);}private static Map<String,String>map(Object o,String n)throws ReflectiveOperationException{Map<String,String>x=new TreeMap<>();for(var e:((Map<?,?>)get(o,n)).entrySet())x.put(sig(e.getKey()),sig(e.getValue()));return Collections.unmodifiableMap(x);}private static Map<String,String>stringMap(Object o,String n)throws ReflectiveOperationException{Map<String,String>x=new TreeMap<>();for(var e:((Map<?,?>)get(o,n)).entrySet())x.put(String.valueOf(e.getKey()),String.valueOf(e.getValue()));return Collections.unmodifiableMap(x);}
 private R4Heuristic2AdapterBridge(){}
}
